### ISSUE TITLE
Dropdown opens really late and slow (Performance Issues)

### ISSUE THREAD

**Issue by SaadAhmadSaddiqui** [hossein-zare/react-native-dropdown-picker#215]
**Describe the bug**
The dropdown box opens really slow. I'm loading in a list of countries which is quite big. I tried another picker and that one opens it quite fast. But I really like your library so I was hoping there would be a fix for it.

**To Reproduce**
Use picker with a 200+ list of items

Create an expo snack:
https://snack.expo.io/@gr8/54e7e9

It works better on this snack. but try copying this set up onto your android phone and test please.

**Expected behavior**
Opens the dropdown fast and smooth

**Info (please complete the following information):**
 - OS: Android (Haven't checked on iOS)
 - Package version: v4

**Comment by hossein-zare** [comment]
Hello,
Sorry for the late response.

The performance bottleneck is because i've not used `FlatList` to show the items.
ReactNative starts complaning when you use `FlatList` inside another `FlatList` and the yellow warning box will pop up.
I'll try to add `FlatList` in the next version but for now i can only say that it won't work with [Categories (Category Support)](https://github.com/hossein-zare/react-native-dropdown-picker#category-support).

**Comment by SaadAhmadSaddiqui** [comment]
Is it because of the category support that this performance drop has come about? Maybe if the performance is better in the v3, can I download that version?

**Comment by hossein-zare** [comment]
No, I just need to change `ScrollView` to `FlatList`

**Comment by SomnathKadam** [comment]
can please do, and can one feature for drop down, drop down should open in modal, so user will select value easily

**Comment by hossein-zare** [comment]
**v5.x** is out with `modal` list mode.

**Comment by umairm1alik** [comment]
If I use listemode = 'SCROLLVIEW'  it makes dropdown performance very slow and if I use 'FLATLIST'  dropdown become not scrollable plus virtualization warning.
