### ISSUE TITLE
Unable to reset the selected value

### ISSUE THREAD

**Issue by RukshanWithanage** [hossein-zare/react-native-dropdown-picker#226]
I tried using `this.controller.reset();` method but nothing happened, and also I tried with `this.controller.null();`

**Comment by Jurpp** [comment]
Are you trying to remove the selection so that the placeholder text is displayed again?  
If so: I got the same problem.  

Besides your attempts I also tried setting the selected item directly:  
`this.controller.selectItem({
                                label: null,
                                value: null,
                                icon: () => {}
                            });
` and removing the currently selected item using `this.controller.removeItem(selectedItem)`.  

Whatever I do I cannot get back to the default state of the picker showing the placeholder text. I am using a single selection, setting the default value using a statefull variable and using items with an integer as value. I created a Snack to based on an example by the library author to show exactly what I'm doing: https://snack.expo.io/9nL2dW-gM

**Comment by hossein-zare** [comment]
Hello @RukshanWithanage, Please show me your code.

**Comment by hossein-zare** [comment]
Hello @Jurpp ,
Here's what you want.
https://snack.expo.io/oKSkdgxeS

**Comment by Jurpp** [comment]
@hossein-zare Awesome, big ups for the fast response!

**Comment by stanislaugh** [comment]
Hi there! Tons of thanks for the component.

I have the same issue with `resetItems`. Seems like it is broken since version 3.6.6. I went down into the version history and found that my following code works fine in 3.6.5 but doesn't work any more in 3.6.6 and later. 

```
let controller = null;

updateItems = () => {
  controller.resetItems([{ value: '3', label: '3' }, { value: '4', label: '4' }], '3');
}

return (
  <>
  <DropDownPicker
    items={[{ value: '1', label: '1' }, { value: '2', label: '2' }]}
    controller={instance => controller = instance}
    defaultValue={'1'}
  />
  <TouchableOpacity onPress={updateItems}>
    <Text>Update</Text>
  </TouchableOpacity>
  </>
);
```

Hope this will help to investigate and find a solution.

**Comment by hossein-zare** [comment]
Hello @stanislaugh ,
You need to define the `onChangeItem` and `onChangeList` properties.
Skipping props that are mentioned in the docs (example) will result in unexpected behaviors.

https://github.com/hossein-zare/react-native-dropdown-picker#controller

**Comment by adhip94** [comment]
@hossein-zare Does this `controller` property exist in the latest version (5.1.25)? It shows that the `DropDownPickerProps` does not have a property called `controller`...

**Comment by mikehardy** [comment]
@adhip94 what did you see when you inspected the code here in this open source module where the code is all available for inspection? 🤔

**Comment by alireza-rg** [comment]
hi how reset the selected value in a new version?

**Comment by ddikodroid** [comment]
> hi how reset the selected value in a new version?
```
 onClose={() => setValue(null)}
