### ISSUE TITLE
Android : onChangeItem is not called when I select an item

### ISSUE THREAD

**Issue by b-allard** [hossein-zare/react-native-dropdown-picker#25]
**Describe the bug**
On Android the onChangeItem is not called when I select an item.
Works on iOS.

I have upgraded the package 2.1.3 to 3.0.4 and I stil have the issue.

**Info (please complete the following information):**
 - OS: [Android]
 - Package version [2.1.3, 3.0.4]

I have tried with the example on snack.expo.io, the example in the README,  no changed, I still have the issue :'(

That's never works on Android.

Please help me, 

Thanks in advance

**Comment by hossein-zare** [comment]
Hello @b-allard ,
Most likely it's because of `zIndex` causing that behavior.
https://github.com/hossein-zare/react-native-dropdown-picker#zindex-conflicts-untouchable-items-overlapping-pickers

Add your Code Snippet with the `containerStyle` property.

`+ onChangeItem` (Updated)
https://snack.expo.io/@hossein-zare/dropdown-zindex

**Comment by b-allard** [comment]
Thank you very much, actually it was a zIndex story from a top view that was set and I hadn't seen it. The condition for Android works perfectly :)
