### ISSUE TITLE
Dynamically update drop down items based on another dropwdown

### ISSUE THREAD

**Issue by furkankaya1** [hossein-zare/react-native-dropdown-picker#369]
(I am new to react native and front end development in general, please excuse my naivety.)

Is it possible to dynamically update drop down items based on another dropdown?

For e.g if I have a dropdown picker for countries and and other dropdown picker  for cities. If i pick "US" in the countries dropdown then the cities dropdown will show me the US cities or if I pick UK then it will show me UK cities. Is there a small example I could see?

**Comment by Kamani** [comment]
@furkankaya1 You are asking for example. And it is not an issue. To understand how to use please refer official documentation.
https://hossein-zare.github.io/react-native-dropdown-picker-website/

And the question you have asked is basic programming thing. Select value from previous dropdown and query for new dropdown when value is selected. You can easily achieve it with state and hooks.

**Comment by hossein-zare** [comment]
Too late but this example is what you need (not exactly):
https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/tutorials/close-other-pickers
https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/usage#setitems

Instead of `setCityOpen`, You should do `setCityItems([...]);` (of course create those state variables)
