### ISSUE TITLE
Please publish changes after pull request

### ISSUE THREAD

**Issue by tek256** [hossein-zare/react-native-dropdown-picker#379]
Hey, 
After pull request  #378 fixed the bug, the change is currently not available in the npm registry. Please publish the change!

Thanks,
Devon

Edit: Also discovered with previous pull request, updated with #380

**Comment by mikehardy** [comment]
Well @tek256 I guess it was sort of fortuitous #378 did not publish since it needed #380 ;-)
More seriously  @hossein-zare - it looks like there is a valid publish workflow here, even if I had access (as a new collaborator) here to hit a button (usually via an `on` `workflow_dispatch` entry in the workflow) it appears releases to npmjs are actually triggered here via creating a github release? Is that accurate?

Thinking ahead: I've had success with semantic-release in the past and it sure is a fix-->publish cycle accelerator. I could look into proposing that as a change here if you like, so that the whole effort around publishing goes to zero and all maintainer effort may be focused entirely on PR review/testing

**Comment by hossein-zare** [comment]
@mikehardy Yeah, Create a new GitHub release.

Steps:
1. Merge **dev-5.x** ➜ **5.x** (Pull Request)
2. Create a release **(Target: 5.x) (Tag name & Release title: v5.x.x)**

>Thinking ahead: I've had success with semantic-release in the past and it sure is a fix-->publish cycle accelerator. I could look into proposing that as a change here if you like, so that the whole effort around publishing goes to zero and all maintainer effort may be focused entirely on PR review/testing

Not sure for now. :/
I think doing it manually is better than automated versioning for this package.
I'll check it out.

**Comment by mikehardy** [comment]
I used to think manual releasing was better as well but I have changed my mind as I attempt to scale my efforts across a great deal more software. The effort is the same (you must verify PRs are good before merging, same as before), it's just all the other stuff disappears. Philosophically, testing effort really is the same it is just that if you have doubts you have to check them pre-merge rather than "merge something then see something that needs fixing then release". With the failure case being "okay merge a fix and release again" - but version numbers are free on the internet (they just give them away ;-) ) so the failure case isn't a big deal either.

This helps a lot for the verification case when it's needed: https://cli.github.com/manual/gh_pr_checkout

But please understand, I'm just talking about workflows I have used that - for me - save me time and result in me releasing more frequently. These are all opinions, and even if backed by evidence they are questions of taste and style, making a new release manually is really easy as well and automating releases would be a medium- / longer-term goal, not something to do now

So! I will follow your steps and see what it's like to try to drive a release here while it's early in the week and I have time to pick up any pieces if I break something (hopefully not :crossed_fingers: )

**Comment by mikehardy** [comment]
I see my release did not work, I believe I need to change package.json version too prior to publish

```
Run npm publish
  npm publish
  shell: /usr/bin/bash -e {0}
  env:
    NPM_CONFIG_USERCONFIG: /home/runner/work/_temp/.npmrc
    NODE_AUTH_TOKEN: ***
npm notice 
npm notice 📦  react-native-dropdown-picker@5.1.21
npm notice === Tarball Contents === 
```

I will increment package.json and retry

**Comment by mikehardy** [comment]
Confirmed - I can see the trail of previous publishes: #356 - I'm on it

**Comment by mikehardy** [comment]
Success! 5.1.23 is live https://github.com/hossein-zare/react-native-dropdown-picker/runs/3172718802?check_suite_focus=true

I'll check over docs and propose whatever seems right with regard to documenting release process. Cheers

**Comment by hossein-zare** [comment]
> I see my release did not work, I believe I need to change package.json version too prior to publish
> 
> ```
> Run npm publish
>   npm publish
>   shell: /usr/bin/bash -e {0}
>   env:
>     NPM_CONFIG_USERCONFIG: /home/runner/work/_temp/.npmrc
>     NODE_AUTH_TOKEN: ***
> npm notice 
> npm notice 📦  react-native-dropdown-picker@5.1.21
> npm notice === Tarball Contents === 
> ```
> 
> I will increment package.json and retry

Sorry, I'd forgotten to mention the `package.json` step.
