### ISSUE TITLE
Dropdown is missing a border at the bottom

### ISSUE THREAD

**Issue by henrybzhang** [hossein-zare/react-native-dropdown-picker#392]
**Bug**
The dropdown is cut on bottom even though there is plenty of space below to display it. This is similar to #190 but seems to be different since the dropdown is not at the bottom of the screen.

**Expected behavior**
Full dropdown is visible

**Screenshot**
![Screenshot_20210811-115524-697](https://user-images.githubusercontent.com/5005277/129071944-48bc0adf-c0ff-4107-9c51-238381758914.png)

**Info**
OS: Android
Package version 5.1.23

**Comment by mikehardy** [comment]
Please post an App.js sufficient to re-create this issue - https://stackoverflow.com/help/minimal-reproducible-example - otherwise we'll have to close it as "not enough information"

It looks to me like you have something else in the view hierarchy overlapping the dropdown, that is to say, the typical zindex problems that many people seem to have when doing complex layouts and using this library.

**Comment by henrybzhang** [comment]
It seems like It is the same issue in #190. I just need to add a parent view to extend down the screen.

**Comment by Dimasprog** [comment]
Try `disableBorderRadius={false}`
