### ISSUE TITLE
Unable to populate defaultValue when pulling list items asyncronously

### ISSUE THREAD

**Issue by justinwerd** [hossein-zare/react-native-dropdown-picker#467]
Is there a preferred method for dealing with asyncronously loaded data? I'm currently pulling data when the user searches with the dropdown, but since its a form field, I also need to be able to populate the defaultValue ahead of time.

**Comment by mikehardy** [comment]
:thinking: you can't populate a component with a value that doesn't exist, but you may re-render once you have results, with a defaultValue that is from the async source. So you need a placeholder-while-async-fetching defaultValue in state I guess, and a useEffect that does the async (or better, react-query package and a useQuery to do the fetch and handle all the terrible async-in-useEffect work you have to do otherwise)
