### ISSUE TITLE
Change the checked icon color of the selectItem.

### ISSUE THREAD

**Issue by yoonachen** [hossein-zare/react-native-dropdown-picker#491]
As title, I wanna change the icon color. Is there any method I can change that?
Thanks!

**Comment by hisamafahri** [comment]
@yoonachen With the current version, you can't do that with the provided icon, since it's using a `png` file. [See here](https://github.com/hossein-zare/react-native-dropdown-picker/blob/4c5fb2f3d7606e5cf37908ebcba840e688cdfb96/src/themes/light/index.js#L10)

But, as [the docs](https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/advanced/icons#tickiconcomponent) mentioned, you can add your own icon and customize it as you wish. Such as:

```tsx
// MyIcon.tsx

import * as React from "react";
import Svg, { Path } from "react-native-svg";

function MyIcon(props: any) {
    return (
        <Svg
            width={24}
            height={24}
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
            {...props}
        >
            <Path
                d="M5 12l5 5L20 7"
                stroke={props.strokeColor}
                strokeWidth={2}
                strokeLinecap="round"
                strokeLinejoin="round"
            />
        </Svg>
    );
}

export default MyIcon;
```

```tsx
// In the DropDownPicker component
import MyIcon from './MyIcon'; // Path to MyIcon.tsx
...
<DropDownPicker
    ...
    TickIconComponent={({style}) => <MyIcon strokeColor='#FF0000' />}
    ...
/>
...
```

**Comment by yoonachen** [comment]
Okay. Thanks for your response!

**Comment by yoonachen** [comment]
Hey, is there has a property to hidden the original icon?

Sorry for my fool question! 
I found the solution `showTickIcon={true}`

**Comment by hemanshum** [comment]
> ```tsx
> strokeColor
> ```

To change the icon color, you can use "tintColor"
`<DropDownPicker
        tickIconStyle={{tintColor: 'red'}}`

**Comment by hemanshum** [comment]
> As title, I wanna change the icon color. Is there any method I can change that? Thanks!

You can color the tick icon using "tintColor"
`<DropDownPicker
          tickIconStyle={{tintColor: 'red',}}`
