### ISSUE TITLE
Strange style of selected Item

### ISSUE THREAD

**Issue by Snotax** [hossein-zare/react-native-dropdown-picker#499]
I have a strange white row under the selected item. Does anybody know how to get rid of this ? 

![image](https://user-images.githubusercontent.com/11430940/150738299-51ec2e29-92a6-4bbd-9961-8bb6f27885e2.png)

**Comment by hossein-zare** [comment]
Please provide your code and items.

**Comment by Snotax** [comment]
@hossein-zare 

Dropdown:  
![image](https://user-images.githubusercontent.com/11430940/150763302-f0e86a97-94d8-4eea-a98d-4c8921c36095.png)

![image](https://user-images.githubusercontent.com/11430940/150763271-aa4fb34f-a2c0-4c19-9c6e-0509e39c0dea.png)

Data:
![image](https://user-images.githubusercontent.com/11430940/150763239-28b6a905-a2a1-4cdf-8fcc-17fdf0aa2f64.png)

**Comment by hossein-zare** [comment]
I created a snack with your code here: https://snack.expo.dev/vtgmJCF6m

But there was nothing to be fixed.

Add `selectedItemContainerStyle={{ backgroundColor: 'red' }}` to your picker to see if it's an item or `Alles` itself.
Extend the width in `containerStyle` or remove it.
Comment out the `onSelectItem` prop.

By the way, Are you getting the items from a remote source or hard-coded because of providing data?
If so, please log the items first and make sure nothing is wrong with the them.

You may end up with something like this:
```js
[
    {label: 'Alles', value: 0},
    {label: undefined, value: undefined},
    {label: 'Lektionen', value: 1},
    {label: 'Kompetenzen', value: 2},
    {label: 'Personen', value: 3},
    {label: 'Raume', value: 4},
]
```

**Comment by Snotax** [comment]
I'm just using dummy data at the moment, so nothing is wrong with the data.
But you were right if I add the backgroundcolor it looks like this:
![image](https://user-images.githubusercontent.com/11430940/150771459-ff624206-8f16-48b5-9cc5-38d8dca2ea8a.png)

So is this default behaviour or can this be disabled?

**Comment by hossein-zare** [comment]
No not default.

Try:
```
showArrowIcon={false}
showTickIcon={false}
```
and remove `paddingHorizontal: 10` from `styles.listItemLabelStyle`

Does that happen to all of the items or just `Alles`?

**Comment by Snotax** [comment]
It worked. The showTickIcon={false} fixed it.
![image](https://user-images.githubusercontent.com/11430940/150775752-314333e6-70b9-46c8-9c17-aec21bb904b6.png)

Thank you for your quick support! Awesome!
