### ISSUE TITLE
Picker scrolling freezes when putting it inside a a bordered View

### ISSUE THREAD

**Issue by dacapoo** [hossein-zare/react-native-dropdown-picker#508]
First of all thank you for the great project, I really liked it but unfortunately  I am currently facing some problems with it..

when I put the Picker inside a view that has border styling ( BorderWidth:1 ) or zIndex, the picker scroll function freezes and does not respond to touch.

the Picker scroll functionality works again as soon as I remove the border styling or the zIndex from the parent View.

is there any solution by any chance ?

**Comment by mikehardy** [comment]
Hi there! You should read the rules: https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/rules
For zIndex, I have a prop on the pickers in my project that sets their zindexes, and I toggle them all to a low number by default but then the opened one I set to a high numbered one, that's because view hirerarchies don't work the way people normally think they do, and zindex doesn't cross view hierarchies https://github.com/hossein-zare/react-native-dropdown-picker/issues/376

hope this helps

**Comment by dacapoo** [comment]
@mikehardy sorry  I did not pay attention to that detail.
Thank you for your help 👍
