### ISSUE TITLE
Performance issues, the picker takes more than 2 seconds to open

### ISSUE THREAD

**Issue by dacapoo** [hossein-zare/react-native-dropdown-picker#539]
Hello,

The picker performance is not ideal on Android, the picker takes almost 2 seconds. The behavior is consistent across the whole app
I am using listmode=""SCROLLVIEW"

Is this how the picker is supposed to perform, or I am missing something ? 

The video that demonstrates that ->  https://drive.google.com/file/d/1WIHgdudlMT1gTE7OIieks8n4cYtTwovi/view?usp=sharing

**Comment by hossein-zare** [comment]
Hello,

I think it's because you have many pickers with frequently rendered items, Every time you open a picker the items are recreated.
As a developer / programmer / software engineer, You should find bottlenecks and optimize your code.

```jsx
// ✔
useEffect(() => {
    setItems1(...);
    setItems2(...);
    setItems3(...);
    ...
}, []);

// ❌
const [items1, setItems1] = useState(...);
const [items2, setItems2] = useState(...);
const [items3, setItems3] = useState(...);
...
```

You should also read articles about how to optimize react / react native apps.

**Comment by kafeelkhatri** [comment]
Its happening with me too is it possible to show a loader when i click on a picker and hide loader when picker opens ?
